# Generated by Django 3.0 on 2019-12-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=20)),
                ('course_section_code', models.IntegerField()),
                ('course_department', models.CharField(max_length=20)),
                ('course_instructor_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GraduationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=30)),
                ('graduation_year', models.CharField(max_length=50)),
                ('four_year_grade_rate', models.FloatField()),
                ('five_year_grade_rate', models.FloatField()),
                ('six_year_grade_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
