# Generated by Django 3.0 on 2019-12-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='course_idd',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_idd',
        ),
    ]
