# Generated by Django 3.0 on 2019-12-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0002_auto_20191209_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_idd',
            new_name='course_no',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_idd',
            new_name='student_no',
        ),
    ]
