# Generated by Django 3.0 on 2019-12-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0003_auto_20191209_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_no',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
