# Generated by Django 3.0 on 2019-12-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0004_auto_20191209_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_no',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_no',
            new_name='student_id',
        ),
    ]
