# Generated by Django 3.0 on 2019-12-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0006_auto_20191209_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.Student')),
            ],
        ),
    ]
