# Generated by Django 3.0 on 2019-12-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0007_studentcourseenrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCourseEnrollment',
        ),
    ]
