# Generated by Django 3.0 on 2019-12-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0008_delete_studentcourseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='fyp.Course'),
        ),
    ]
